### PR TITLE
Update scrap.py

### PR DESCRIPTION
**Pull request by SAJI-01**

### CODE REVIEW

**Comment by mhdzumair** [comment]
Hi @SAJI-01 thanks for your contribution. i haven't used this add-on for a while. Is it still working?

**Comment by SAJI-01** [comment]
Nope, it's not. I tried to make it work but it didn't work.

**Comment by mhdzumair** [comment]
Ohh okay. Currently i only maintain MediaFusion add-on. You are welcome to make any contribution to that.

**Comment by SAJI-01** [comment]
Ok, thanks for the clarification.

**Pull request closed without merging**
